language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
notifications:
  email:
    recipients:
      - justin@justinholmes.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#hendrix"
    template:
      - "%{repository_slug} (%{branch} - %{commit} - %{commit_message} - %{author} - %{message})"
      - "Build details: %{build_url}"
      - "Result: %{result}"
    use_notice: true
script: python runtests.py
